#!/bin/bash

set -e
set -o pipefail

if test -d ./deploy
	then
		rm -R ./deploy
fi

mdtool build ./Packages.mdproj
for a in `ls -1 ./deploy/*.tar`; do tar -xvf $a -C ./deploy/; done
rm ./deploy/*.tar

cd deploy/MarkdownBlog
rsync -avzR --delete . root@george.softumus.com:/var/www/george.softumus.com
cd ../..

ssh root@george.softumus.com < ./tools/deploy-remote

